#!/usr/bin/env python3
"""Build the cross-modality (state vs pixel) comparison table."""
from pathlib import Path
ROOT = Path("/home/lx/snn")
OUT = ROOT / "results/aggregate/cross_modality_table.md"
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("""# Cross-Modality Table (state vs pixel, v0.7.15)

> Generated by `code/scripts/generalist_v0_7_5_5m_pixel/cross_modality_table.py`.
> Compares `generalist_5m_table.md` (state, 130 ckpts) and `generalist_5m_pixel_table.md` (pixel, 130 ckpts).

## Per-model cross-modality comparison

| Model | state (env-SR / LeWM-SR) | pixel (env-SR / LeWM-SR) | Delta env-SR | Delta LeWM-SR |
|-------|---|---|---|---|

(Filled in by re-aggregating both tables once they are populated.)
""")
print(f"Stub: {OUT}")
