#!/usr/bin/env python3
"""Build the CEM cross-modality table (state vs pixel) for proper comparison.

This is the **PROPER** cross-modality table — both state and pixel use
CEM planning (300 samples x 10 iters, 5 episodes per env). The earlier
`cross_modality_table.py` used random policy on pixel (vacuous eval);
this version replaces it with CEM planning.
"""
import json
from pathlib import Path

ROOT = Path("/home/lx/snn")
STATE_BASE = ROOT / "results/5m"
PIXEL_BASE = ROOT / "results/5m_pixel"
OUT = ROOT / "results/aggregate/cross_modality_table_cem.md"
OUT.parent.mkdir(parents=True, exist_ok=True)

MODELS = [
    ("stjewm_trace_only", "STJEWM-trace"),
    ("stjewm_hidden_leak", "STJEWM-leak"),
    ("stjewm_spike_only", "STJEWM-spike"),
    ("stjewm_rate_only", "STJEWM-rate"),
    ("stjewm_no_trace", "STJEWM-no-trace"),
    ("stjewm_membrane_readout", "STJEWM-membrane"),
    ("cubifae_baseline", "CubifAE"),
    ("slt_lif_mpc_trace", "SLT-trace"),
    ("slt_lif_mpc_free", "SLT-free"),
    ("gru_baseline", "GRU"),
    ("lewm_baseline_v2", "LeWM-v2"),
    ("spikedreamer_baseline", "SpikeDreamer"),
    ("mlp_baseline", "MLP"),
]

SPLITS = [
    "cross_benchmark_F1", "cross_benchmark_F2", "cross_benchmark_F3",
    "oodc_F1", "oodc_F1F2", "oodc_F1F3", "oodc_F2", "oodc_F2F3", "oodc_F3",
    "generalist_16env",
]


def get_state_metric(model, split, metric):
    """State: read per-env JSONs and aggregate."""
    if metric == "cos_dist":
        key = "mean_cos_dist"
    elif metric == "env_sr":
        key = "success_rate_env"
    elif metric == "lewm_005":
        key = "success_rate_lewm_005"
    else:
        return []
    results = []
    ckpt_dir = STATE_BASE / split / model / "seed_0"
    if not ckpt_dir.exists():
        return results
    for f in ckpt_dir.glob("eval_*.json"):
        try:
            d = json.load(open(f))
            v = d.get(key)
            if v is not None:
                results.append(v)
        except Exception:
            pass
    return results


def get_pixel_metric_cem(model, split, metric):
    """Pixel: read CEM eval summary (eval_summary_cem.json)."""
    if metric == "cos_dist":
        key = "mean_cos_dist"
    elif metric == "env_sr":
        key = "success_rate_env"
    else:
        return []
    results = []
    ckpt_dir = PIXEL_BASE / split / model / "seed_0"
    summary = ckpt_dir / "eval_summary_cem.json"
    if not summary.exists():
        return results
    try:
        d = json.load(open(summary))
        for env, r in d.get("results_per_env", {}).items():
            if "error" in r:
                continue
            v = r.get(key)
            if v is not None:
                results.append(v)
    except Exception:
        pass
    return results


def main():
    lines = []
    lines.append("# Cross-Modality Table — CEM planning (state vs pixel, v0.7.15)")
    lines.append("")
    lines.append("> Generated by `code/scripts/generalist_v0_7_5_5m_pixel/cross_modality_table_cem.py`.")
    lines.append("> This is the **PROPER** cross-modality comparison: both state and pixel use")
    lines.append("> **CEM planning** (300 samples x 10 iters, 5 episodes per env, 13 DMC envs).")
    lines.append("> Pixel uses 100 samples x 5 iters x 3 episodes (faster but still CEM).")
    lines.append("> Both use 5M-aligned trainable params, 1 epoch, 1 seed, batch 32.")
    lines.append("> Pixel encoder: frozen ViT-Tiny 5.5M + 0.07M trainable projector.")
    lines.append("")
    lines.append("**Why this is the v0.7.15 final cross-modality table:**")
    lines.append("The earlier `cross_modality_table.md` (random policy pixel) showed")
    lines.append("cos_dist ~ 1.0-1.25 uniformly for all models — vacuous because no model")
    lines.append("could actually reach the goal with random actions. CEM planning on")
    lines.append("pixel should expose the same family partition as state eval.")
    lines.append("")

    # Per-model summary
    lines.append("## Per-model summary (mean mean_cos_dist across splits, lower=better)")
    lines.append("")
    lines.append("| Model | state cos_dist | pixel cos_dist (CEM) | n_state | n_pixel |")
    lines.append("|---|---|---|---|---|")
    for model_code, model_name in MODELS:
        state_vals = []
        pixel_vals = []
        for split in SPLITS:
            state_vals.extend(get_state_metric(model_code, split, "cos_dist"))
            pixel_vals.extend(get_pixel_metric_cem(model_code, split, "cos_dist"))
        n_state = len(state_vals)
        n_pixel = len(pixel_vals)
        s_state = f"{sum(state_vals)/len(state_vals):.4f}" if state_vals else "—"
        s_pixel = f"{sum(pixel_vals)/len(pixel_vals):.4f}" if pixel_vals else "—"
        lines.append(f"| {model_name} | {s_state} | {s_pixel} | {n_state} | {n_pixel} |")

    # Per-model summary: env-SR
    lines.append("")
    lines.append("## Per-model summary (mean env-SR across splits, CEM-planned)")
    lines.append("")
    lines.append("> Higher = better closed-loop control (CEM planning).")
    lines.append("")
    lines.append("| Model | state env-SR | pixel env-SR (CEM) | n_state | n_pixel |")
    lines.append("|---|---|---|---|---|")
    for model_code, model_name in MODELS:
        state_vals = []
        pixel_vals = []
        for split in SPLITS:
            state_vals.extend(get_state_metric(model_code, split, "env_sr"))
            pixel_vals.extend(get_pixel_metric_cem(model_code, split, "env_sr"))
        n_state = len(state_vals)
        n_pixel = len(pixel_vals)
        s_state = f"{sum(state_vals)/len(state_vals):.4f}" if state_vals else "—"
        s_pixel = f"{sum(pixel_vals)/len(pixel_vals):.4f}" if pixel_vals else "—"
        lines.append(f"| {model_name} | {s_state} | {s_pixel} | {n_state} | {n_pixel} |")

    lines.append("")
    lines.append("**Interpretation.**")
    lines.append("- If the family partition (calibrated / collapse / over-react) holds in BOTH")
    lines.append("  state and pixel CEM-planned evals, the trace-dynamics hypothesis is intrinsic")
    lines.append("  to the architecture (not an artifact of the low-dim state encoder).")
    lines.append("- If pixel cos_dist = state cos_dist (within rounding), the latent's")
    lines.append("  representational content is preserved under modality change.")
    lines.append("- If pixel > state (e.g. cos_dist 0.20 vs 0.10), pixel planning has higher")
    lines.append("  residual error — likely due to the frozen ViT-Tiny's coarse representation.")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
