#!/usr/bin/env python3
"""Build the cross-modality (state vs pixel) table - using mean_cos_dist for both."""
import json
from pathlib import Path

ROOT = Path("/home/lx/snn")
STATE_BASE = ROOT / "results/5m"
PIXEL_BASE = ROOT / "results/5m_pixel"
OUT = ROOT / "results/aggregate/cross_modality_table.md"
OUT.parent.mkdir(parents=True, exist_ok=True)

MODELS = [
    ("stjewm_trace_only", "STJEWM-trace"),
    ("stjewm_hidden_leak", "STJEWM-leak"),
    ("stjewm_spike_only", "STJEWM-spike"),
    ("stjewm_rate_only", "STJEWM-rate"),
    ("stjewm_no_trace", "STJEWM-no-trace"),
    ("stjewm_membrane_readout", "STJEWM-membrane"),
    ("alif_timecell_baseline", "ALIFTimecell"),
    ("stacked_lif_trace", "Stacked-LIF-trace"),
    ("stacked_lif_free", "Stacked-LIF-free"),
    ("gru_baseline", "GRU"),
    ("lewm_baseline_v2", "LeWM-v2"),
    ("lif_transformer_baseline", "LIFTransformer"),
    ("mlp_baseline", "MLP"),
]

SPLITS = [
    "cross_benchmark_F1", "cross_benchmark_F2", "cross_benchmark_F3",
    "oodc_F1", "oodc_F1F2", "oodc_F1F3", "oodc_F2", "oodc_F2F3", "oodc_F3",
    "generalist_16env",
]


def get_state_metric(model, split, metric):
    """State: read per-env JSONs and aggregate."""
    if metric == "cos_dist":
        key = "mean_cos_dist"
    elif metric == "lewm_005":
        key = "success_rate_lewm_005"
    elif metric == "env_sr":
        key = "success_rate_env"
    else:
        return []
    results = []
    ckpt_dir = STATE_BASE / split / model / "seed_0"
    if not ckpt_dir.exists():
        return results
    for f in ckpt_dir.glob("eval_*.json"):
        try:
            d = json.load(open(f))
            v = d.get(key)
            if v is not None:
                results.append(v)
        except Exception:
            pass
    return results


def get_pixel_metric(model, split, metric):
    """Pixel: read summary JSON."""
    if metric == "cos_dist":
        key = "mean_cos_dist"
    elif metric == "env_sr":
        key = "success_rate_env"
    else:
        return []
    results = []
    ckpt_dir = PIXEL_BASE / split / model / "seed_0"
    if not ckpt_dir.exists():
        return results
    summary = ckpt_dir / "eval_summary.json"
    if not summary.exists():
        return results
    try:
        d = json.load(open(summary))
        for env, r in d.get("results_per_env", {}).items():
            if "error" in r:
                continue
            v = r.get(key)
            if v is not None:
                results.append(v)
    except Exception:
        pass
    return results


def main():
    lines = []
    lines.append("# Cross-Modality Table (state vs pixel, v0.7.15)")
    lines.append("")
    lines.append("> Generated by `code/scripts/generalist_v0_7_5_5m_pixel/cross_modality_table.py`.")
    lines.append("> Compares per-ckpt state (v0.7.14) and pixel (v0.7.15) eval results.")
    lines.append("> Both use 5M-aligned trainable params, 1 epoch, 1 seed, batch 32.")
    lines.append("> State eval: CEM with 5 episodes, mean_cos_dist reported.")
    lines.append("> Pixel eval: random policy with 2 episodes × 50 steps, mean_cos_dist reported.")
    lines.append("> env-SR=0 across the board for both (5-step CEM horizon vs 25-step goal is")
    lines.append("> the v0.7.13 bug #3 artifact, NOT a model failure).")
    lines.append("> Training is in progress — table will be filled as 130 ckpts finish.")
    lines.append("")

    # Per-model aggregate: mean across all splits
    lines.append("## Per-model summary (mean mean_cos_dist across splits, lower=better)")
    lines.append("")
    lines.append("| Model | state cos_dist | pixel cos_dist | n_state | n_pixel |")
    lines.append("|---|---|---|---|---|")
    for model_code, model_name in MODELS:
        state_vals = []
        pixel_vals = []
        for split in SPLITS:
            state_vals.extend(get_state_metric(model_code, split, "cos_dist"))
            pixel_vals.extend(get_pixel_metric(model_code, split, "cos_dist"))
        n_state = len(state_vals)
        n_pixel = len(pixel_vals)
        s_state = f"{sum(state_vals)/len(state_vals):.4f}" if state_vals else "—"
        s_pixel = f"{sum(pixel_vals)/len(pixel_vals):.4f}" if pixel_vals else "—"
        lines.append(f"| {model_name} | {s_state} | {s_pixel} | {n_state} | {n_pixel} |")

    lines.append("")
    lines.append("## Per-model summary (mean LeWM-SR @0.05, state-only)")
    lines.append("")
    lines.append("> State-side: LeWM-SR @0.05 = fraction of rollouts where cos_dist < 0.05.")
    lines.append("> High = latent goal-match; low = fail. Range [0, 1].")
    lines.append("")
    lines.append("| Model | state LeWM-SR@0.05 | n_state |")
    lines.append("|---|---|---|")
    for model_code, model_name in MODELS:
        state_vals = []
        for split in SPLITS:
            state_vals.extend(get_state_metric(model_code, split, "lewm_005"))
        n_state = len(state_vals)
        s_state = f"{sum(state_vals)/len(state_vals):.4f}" if state_vals else "—"
        lines.append(f"| {model_name} | {s_state} | {n_state} |")

    lines.append("")
    lines.append("**Interpretation.**")
    lines.append("- State cos_dist: lower = better goal-match. The trace family (STJEWM + ALIF-timecell + SLT)")
    lines.append("  should give cos_dist ~ 0.1 (calibrated); collapse (MLP/LIFTransformer) should give")
    lines.append("  cos_dist ~ 0 (latent=constant); over-react (LeWM-v2) should give cos_dist ~ 0.18.")
    lines.append("- Pixel cos_dist: same interpretation, but the random policy produces larger distances")
    lines.append("  because no real control is happening — the metric still reveals the family partition")
    lines.append("  via the collapse-vs-calibrated-vs-over-react band structure.")
    lines.append("- **Family partition survives modality change** if the rank order of cos_dist across models")
    lines.append("  is preserved between state and pixel (calibrated < noise < over-react < collapse).")

    OUT.write_text("\n".join(lines))
    print(f"Wrote {OUT} ({len(lines)} lines)")


if __name__ == "__main__":
    main()
